### ISSUE TITLE
Hide preroll libraries from Home page

### ISSUE THREAD

**Issue by dheian** [CherryFloors/jellyfin-plugin-cinemamode#18]
Just wondering if there's a way to hide the pre-roll libraries so that they're still accessible by the plugin but don't show up on the Home page next to Movies, Shows, Music, etc.

Thanks.

**Comment by CherryFloors** [comment]
Unfortunately no, at least none that I am aware of at the moment. This is next on my roadmap though. When making the switch to libraries, to provide the meta data based selection, I briefly looked for a way to hide certain libraries from everyone but the Admin while still allowing the plugin to show content from it to all users (I had done this with Channels before but this always felt too hacky and the wrong way to organize this type of content).

I will need to do a deep dive into the Jellyfin source code to get a sense if this is even possible with a plugin and it could be time consuming. I didn't want this to hold up the release of the updated plugin because alot of work was done to provide the new selection options. I thought it best to get the new version out there. I'll mark this as an enhancement and keep the thread open. Not sure when I'll get to it but it will be the next thing I do. Hope you enjoy the plugin and thanks for starting the discussion!

**Comment by CherryFloors** [comment]
Also, what I have done in the mean time is name my pre-roll libraries "z Trailer Pre-Rolls" and "z Feature Pre-Rolls" so they appear at the end of the library list by default. It's far from a perfect  workaround.

**Comment by dheian** [comment]
Great. I look forward to checking it out.

**Comment by OMGButterbee** [comment]
I'm glad you're looking into this! In the meantime the "far from a perfect workaround" of naming the libraries starting with z actually does help so thank you for that suggestion

**Comment by FabianBartl** [comment]
You can hide the libraries from the homepage and the sidebar by adding the following CSS snippet:

```css
/* hide pre-roll libraries */
[data-id="3862c9622408b2bb528d4603737113a4"], [data-itemid="3862c9622408b2bb528d4603737113a4"],
[data-id="dc9531519b809a4d79d060d3056f3e1a"], [data-itemid="dc9531519b809a4d79d060d3056f3e1a"] {
    display: none !important;
}
```

`data-id` is used by the card box on the homepage and `data-itemid` by the entries in the sidebar. The values are just the library IDs, you find them in their URL parameter `topParentId`.
